### ISSUE TITLE
Initializing

### ISSUE THREAD

**Issue by emorling** [Ahrengot/autoheight-textarea#5]
The functionality is great! I am using reactstrap Input, and getting

`<autoheight-textarea> needs a <textarea> child in order to initialize`

The textarea is not available from start, but rather added later based on user interactiono.

Is there any way to programmatically initialize autoheight-textarea by passing it an element?

**Comment by Ahrengot** [comment]
Hey @emorling i'm not sure what you code looks like, but you could conditionally render the entire thing. 

```JavaScript
const component = props => {
  return (
    <div>
      {props.showTextarea && (
        <autoheight-textarea>
          <textarea></textarea>
        </autoheight-textarea>
      )}
    </div>
  )
}
```
